//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BangMa
    {
        public System.Guid Id { get; set; }
        public string Ma { get; set; }
        public string Ten { get; set; }
        public string TienTo { get; set; }
        public int DoDai { get; set; }
        public int SoHT { get; set; }
        public string TienToHT { get; set; }
        public bool HienThiTienTo { get; set; }
    }
}
