//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BienBanNghiemThu
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> IdCongViec { get; set; }
        public Nullable<System.Guid> IdPhieuDeNghi { get; set; }
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public Nullable<System.Guid> IdCanBo { get; set; }
        public string DanhSachKhoa { get; set; }
        public string DauViec { get; set; }
        public string NhaThau { get; set; }
        public string PhongQuanTri { get; set; }
    
        public virtual CanBo CanBo { get; set; }
        public virtual CongViecTheoQuyetDinh CongViecTheoQuyetDinh { get; set; }
        public virtual PhieuDeNghi PhieuDeNghi { get; set; }
    }
}
