//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuDeNghi
    {
        public System.Guid Id { get; set; }
        public System.Guid IdKhoa { get; set; }
        public System.DateTime NgayTao { get; set; }
        public System.Guid TrangThai { get; set; }
        public string NoiDung { get; set; }
        public System.Guid IdCanBoDeNghi { get; set; }
        public Nullable<System.Guid> IdCanBoThucHien { get; set; }
    
        public virtual CanBo CanBoDeNghi { get; set; }
        public virtual CanBo CanBoThucHien { get; set; }
        public virtual KhoaPhong KhoaPhong { get; set; }
    }
}
