$.fn.datepicker.dates['en'] = {
    days: ["CN","Hai","Ba","Tư","Năm","Sáu","Bảy"],
    daysShort: ["CN", "Hai", "Ba", "Tư", "Năm", "Sáu", "Bảy"],
    daysMin: ["CN","Hai","Ba","Tư","Năm","Sáu","Bảy"],
    months: ["Tháng 1","Tháng 2","Tháng 3","Tháng 4","Tháng 5","Tháng 6","Tháng 7","Tháng 8","Tháng 9","Tháng 10","Tháng 11","Tháng 12"],
    monthsShort: ["T1","T2","T3","T4","T5","T6","T7","T8","T9","T10","T11","T12"],
    today: "Today",
    clear: "Clear",
    format: "dd/mm/yyyy",
    titleFormat: "MM yyyy", /* Leverages same syntax as 'format' */
    weekStart: 0
};